name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      -
        name: Run test
        run: make test
      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      -
        name: fmt
        run: make fmt
      -
        name: doc
        run: make doc
      -
        name: check no diff
        run: |
          if [[ "$(git diff)" = "" ]]; then
            exit 0
          else
            git diff
            echo "Something has changed, please run make fmt doc
            exit 1
          fi